apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: testing-env
  labels:
    app: mysql
    tier: database
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
      tier: database
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
      - name: mysql
        image: kudipudirk/mysql

---

kind: Service
apiVersion: v1
metadata:
  name: mysql-service
  namespace: testing-env
spec:
  selector: # labels are used as selectors
    app: mysql
    tier: database
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306

