kind: Pod
apiVersion: v1
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: Ramakrishna
      value: DevOps
    - name: Weekends
      value: "pratice"
    - name: duration
      value: "1HRS"