kind: Service
apiVersion: v1
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    project: rama
    component: backend
    environment: dev
    version: "1.0.0"
    demo: lb
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: 30007
---
kind: Pod
apiVersion: v1
metadata:
  name: backend-lb
  labels:
    project: rama
    component: backend
    environment: dev
    version: "1.0.0"
    demo: lb
spec:
  containers:
  - name: nginx
    image: nginx
    
