apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: testing-env
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 80           # Exposed port on LoadBalancer
      targetPort: 8080   # App container port
