apiVersion: v1
kind: Namespace
metadata:
  name: testing

---

apiVersion: v1
kind: Services
metadata:
  name: nginx-Service
  namespaces: testing
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

kind: Pod
apiVersion: v1
metadata:
  name: my-Pod
  labels:
    app: my-app
  namespaces: testing
spec:
  containers:
  - name: myprofile
    image: kudipudirk/my-profile

