apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: testing-env
  labels:
    app: frontend
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      tier: web
  template:
    metadata:
      labels:
        app: frontend
        tier: web
    spec:
      containers:
      - name: nginx
        image: kudipudirk/frontend
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 0
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
    tier: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
